<?php

use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformSubmissionForm;
use Drupal\Core\Serialization\Yaml;
use Drupal\webform\Entity\WebformSubmission;
//use Symfony\Component\Yaml\Yaml;



/**
 * Implements hook_form_alter().
 */

function checklist_task_page_attachments_alter(array &$attachments)
{
  $gid =0;
  $fields =[];
  $url = \Drupal::service('path.current')->getPath();
  $arguments = explode('/', $url);
  foreach ($arguments as $value) {
    if (is_numeric($value)) {
      $gid=$value;
      break;
    }
  }

  if ($gid!=0 && $url == '/group/'.strval($gid)){
    $existe = revisiongrouptareas($gid);
    if ($existe!=[]){
      $ext_web = revisionwebform($gid);
      if ($ext_web!=[]){
        $fields = extraetareas($gid);
        editwebform($gid,$fields[1]);
      }else{
        $fields = extraetareas($gid);
        webform_function($fields[0],$gid,$fields[1]);
      }

    }
  }

}





function revisiongrouptareas($gid){
  $storage = \Drupal::entityTypeManager()->getStorage('group');
  $query = $storage->getQuery()
    ->condition('type','tareas')
    ->condition('status',1);
  $ids = $query->execute();
  $resultados = !empty($ids) ? $storage->loadMultiple($ids):NULL;
  foreach ($resultados as $resultado){
    if ($resultado->id() == $gid){
      return 1;
    }

  }
  return;
}


function revisionwebform($gid){
  $storage = \Drupal::entityTypeManager()->getStorage('webform');
  $query = $storage->getQuery();
  $ids = $query->execute();
  $resultados = !empty($ids) ? $storage->loadMultiple($ids):NULL;
  foreach ($resultados as $resultado){
    if ($resultado->id() == $gid){
      return 1;
    }

  }
  return;
}


function extraetareas($gid){
  $group = \Drupal::entityTypeManager()->getStorage('group')->load($gid);
  $title = $group->label();
  $field_tareas = $group->get('field_tareas')->getValue();
  $log = sizeof($field_tareas);
  for ($i=0;$i<$log;$i++){
    $opciones[$i]= $field_tareas[$i]['value'];
  }
  $field[0]=$title;
  $field[1]=$opciones;

  return $field;
}


function webform_function($title,$gid,$options){

  $elements = [
    'Actividades'=> [
      '#type'=>'checkboxes',
      '#title'=> 'Actividades',
      '#options' =>$options,
    ]
  ];
  $settings =[

  ];

  $settings=Webform::getDefaultSettings();

// Create a webform.
  $webform = Webform::create([
    'id' => $gid,
    'title' => $title.' - '.$gid,
    'elements' => Yaml::encode($elements),
    'settings'=> $settings,
  ]);
  $webform->save();


}


function editwebform($gid,$options){
  $webform = Webform::load($gid);
  $elements = Yaml::decode($webform->get('elements'));
  $elements['Actividades']= [
      '#type'=>'checkboxes',
      '#title'=> 'Actividades',
      '#options' =>$options,
  ];

  $webform->set('elements', Yaml::encode($elements));
  $webform->save();

}
