<?php



function group_tools_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id=='group_content_empresas-group_membership_add_form'){
    $form['actions']['submit']['#submit'][]='create_empresa_form_submit';
  }
}

function create_empresa_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state){
  deletemember();
}

function deletemember(){
  $i=0;
  $storage = \Drupal::entityTypeManager()->getStorage('group');
  $query = $storage->getQuery();
  $ids = $query->execute();
  $groups = !empty($ids) ? $storage->loadMultiple($ids): NULL;
  if ($groups){
    foreach ($groups as $group){
      $members = $group->getMembers();
      foreach ($members as $member){
        $id_member = $member->getUser();
        if($id_member){
          $id_member=$id_member->id();
        }
        if($id_member ==  \Drupal::currentUser()->id()){
          $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
          $gid = $group->id();
          $group = \Drupal\group\Entity\Group::load($gid);
          $group->removeMember($account);
          $group->save();
          $grupos[$i]=$group;
          $i++;

        }
      }
    }
  }
  $log = sizeof($grupos);
  $group = $grupos[$log-1];
  $type = $group->bundle();
  crearmember($gid,$type);
}

function crearmember($gid,$type){
  $account = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $group = \Drupal\group\Entity\Group::load($gid);
  $values =['group_roles'=>$type.'-'.'direccion_estrategico'];
  $group->addMember($account,$values);
  $group->save();
}
