charts_default_settings:
  library: highcharts
  type: scatter
  display:
    title: Grafico
    colors:
      - '#d8810f'
      - '#0d233a'
      - '#8bbc21'
      - '#910000'
      - '#1aadce'
      - '#492970'
      - '#f28f43'
      - '#77a1e5'
      - '#c42525'
      - '#a6c96a'
    title_position: out
    tooltips: true
    legend_position: right
    background: ''
    dimensions:
      width: ''
      width_units: '%'
      height: ''
      height_units: ''
    gauge:
      max: '100'
      min: '0'
      green_from: '85'
      green_to: '100'
      yellow_from: '50'
      yellow_to: '85'
      red_from: '0'
      red_to: '50'
    data_labels: false
    data_markers: false
    three_dimensional: 0
    polar: 0
  xaxis:
    title: 'Las X'
    labels_rotation: '0'
  yaxis:
    title: 'Las Y'
    min: '1'
    max: '100'
    prefix: ''
    suffix: ''
    decimal_count: ''
    labels_rotation: '0'
  highcharts_settings:
    legend:
      layout: vertical
      background_color: ''
      border_width: '0'
      item_style:
        color: ''
        overflow: ''
      shadow: 0
_core:
  default_config_hash: UKwfW5G0nNY2qqm4N475XsYYDP2et5QfNGIzJAvlho8
langcode: es
